name: iOS

on:
  push:
    branches: [main, develop, hotfix/detox-github-action]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  end-2-end-test:
    name: e2e iOS test
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox clean-framework-cache && yarn detox build-framework-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..

      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: yarn build:e2e-ios-dev-debug
      - run: yarn test:e2e-ios-dev-debug
